config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only:[:new, :create, :show, :index]
  resources :kitchens, only:[:new, :create, :show]
  resources :meals, only:[:new, :create, :show]
  resources :preferences, only:[:new, :create, :show]
end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
  belongs_to :recipe
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :recipe
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true 
  has_many :kitchens
  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  def new
    @kitchen = Kitchen.new
  end

  def create
    @kitchen = Kitchen.new(params.require(:kitchen).permit(:name))
    if @kitchen.save
      redirect_to @kitchen
    else
      flash[:error] = 'Preencher os Campos Obrigatórios'
      render 'new'
    end
  end

  def show
    @kitchen = Kitchen.find(params[:id])
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(params.require(:meal).permit(:name))
    if @meal.save
      redirect_to @meal
    else
      flash[:error] = 'Preencher os Campos Obrigatórios'
      render 'new'
    end
  end

  def show
    @meal = Meal.find(params[:id])
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def new
    @preference = Preference.new
  end

  def create
    @preference = Preference.new(params.require(:preference).permit(:name))
    if @preference.save
      redirect_to @preference
    else
      flash[:error] = 'Preencher os Campos Obrigatórios'
      render 'new'
    end
  end

  def show
    @preference = Preference.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params.require(:recipe).permit(:name, :kitchen, :kind,
                                        :proferably, :serves, :preparation_time,
                                        :level, :ingredients, :step_by_step))
    if @recipe.save
      redirect_to @recipe
    else
      flash[:error] = 'Preencher os Campos Obrigatórios'
      render 'new'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = Recipe.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/kitchens/new.html.erb
<h1>Cadastrar Cozinha</h1>
 <%= simple_form_for @kitchen do |f| %>
 <%= f.input :name, label: 'Cozinha' %>
 <%= f.submit 'Ir para Cadastro' %>
<% end %>

app/views/kitchens/show.html.erb
<strong> Cozinha: </strong>
 <p>
   <%= @kitchen.name %>
 </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Receitas da Vovó </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class='navbar navbar-inverse'>
      <div class='container-fluid'>
        <div class='navbar-header title-logo'>
        <h2><%= link_to 'Receitas da Vovó', root_path %></h2>
        </div>
        <div class='collapse navbar-collapse'>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Cadastrar Receitas', new_recipe_path %> </li>
            <li><%= link_to 'Visualizaar Receitas', recipes_path %> </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meals/new.html.erb
<h1>Cadastrar Tipo</h1>
 <%= simple_form_for @meal do |f| %>
 <%= f.input :name, label: 'Refeição' %>
 <%= f.submit 'Ir para Cadastro' %>
<% end %>

app/views/meals/show.html.erb
<strong> Tipo: </strong>
 <p>
   <%= @meal.name %>
 </p>

app/views/preferences/new.html.erb
<h1>Cadastrar Preferencia</h1>
 <%= simple_form_for @preference do |f| %>
 <%= f.input :name, label: 'Preferencia' %>
 <%= f.submit 'Ir para Cadastro' %>
<% end %>

app/views/preferences/show.html.erb
<strong> Preferencia: </strong>
 <p>
   <%= @preference.name %>
 </p>

app/views/recipes/index.html.erb
<h2>Receitas</h2>

<hr>
<div class="well well-lg">
  <% @recipes.each do |rec| %>
</p>
 <p class="btn btn-default">
   <%= link_to rec.name, recipe_path(rec) %>
 </p>
 <p>
   <strong> Preferencia: </strong>
   <%= rec.proferably %>
 </p>
 <p>
   <strong> Tipo: </strong>
   <%= rec.kind %>
 </p>
 <p>
   <strong> Cozinha: </strong>
   <%= rec.kitchen %>
 </p>
 <p>
   <strong> Dificuldade: </strong>
   <%= rec.level %>
 </p>
<hr>
<% end %>
</div>

app/views/recipes/new.html.erb
<%= flash[:error] %>
<h3>Cadastrar Receita</h3>
<div class="well well-lg">
 <%= simple_form_for @recipe do |f| %>
 <%= f.input :name, label: 'Nome' %>
 <%= f.input :kitchen, label: 'Cozinha' %>
 <%= f.input :kind, label: 'Tipo' %>
 <%= f.input :proferably, label: 'Preferencia' %>
 <%= f.input :serves, label: 'Porções' %>
 <%= f.input :preparation_time, label: 'Tempo de Preparo' %>
 <%= f.input :level, label: 'Dificuldade', collection:['Fácil', 'Médio', 'Dificil'] %>
 <%= f.input :ingredients, label: 'Ingredientes' %>
 <%= f.input :step_by_step, label: 'Modo de Preparo' %>
 <%= f.submit 'Enviar Receita', class:'btn btn-warning' %>
<% end %>
</div>

app/views/recipes/show.html.erb
<section>
<div class="well well-lg">
<h1><%= @recipe.name %></h1>
<hr>
<p>
  <strong> Cozinha: </strong>
   <%= @recipe.kitchen %>
 </p>

  <p>
   <strong> Tipo: </strong>
    <%= @recipe.kind %>
  </p>

  <p>
   <strong> Preferencia: </strong>
    <%= @recipe.proferably %>
  </p>

  <p>
   <strong> Porção: </strong>
    <%= @recipe.serves %>
  </p>

  <p>
   <strong> Tempo de Preparo: </strong>
    <%= @recipe.preparation_time %>
  </p>

  <p>
   <strong> Nivel de Dificuldade: </strong>
    <%= @recipe.level %>
  </p>

  <p>
   <strong> Ingredientes: </strong>
    <%= @recipe.ingredients %>
  </p>

  <p>
   <strong> Modo de Preparo: </strong>
    <%= @recipe.step_by_step %>
  </p>
</div>
</section>

app/views/references/new.html.erb
<h1>Cadastrar Preferencia</h1>
 <%= simple_form_for @preference do |f| %>
 <%= f.input :name, label: 'Preferencia' %>
 <%= f.submit 'Ir para Cadastro' %>
<% end %>